"""富途 OpenAPI 路径常量（唯一事实源）。

锁定测试（tests/test_wp12_transport.py / test_wp12_openapi_package.py）绑定本模块常量与
`docs/superpowers/plans/wp12-endpoint-lock.md`；方法组模块**不得**内联 `/api/v1.0` 字面量
（护栏见 test_wp12_openapi_package.py 的 AST 扫描）——防未核对路径落地。
"""
STOCK_SCREEN_PATH = "/api/v1.0/quote/stock-screen"
WARRANT_SCREEN_PATH = "/api/v1.0/quote/warrant-screen"
PLATE_LIST_PATH = "/api/v1.0/quote/plate-list"
PLATE_STOCK_PATH = "/api/v1.0/quote/plate-stock"
SHORT_DAILY_VOLUME_PATH = "/api/v1.0/quote/{symbol}/short/daily-volume"
SHORT_INTEREST_PATH = "/api/v1.0/quote/{symbol}/short/interest"
ECONOMIC_CALENDAR_HOT_PATH = "/api/v1.0/quote/economic-calendar/hot"
ECONOMIC_CALENDAR_SEARCH_PATH = "/api/v1.0/quote/economic-calendar/search"
OWNER_PLATE_PATH = "/api/v1.0/quote/{symbol}/owner-plate"
REHAB_PATH = "/api/v1.0/quote/{symbol}/corporate-actions/rehab"
IPO_LIST_PATH = "/api/v1.0/quote/ipo-list/{market}"
WATCHLIST_LIST_PATH = "/api/v1.0/quote/user-security"
WATCHLIST_GROUPS_PATH = "/api/v1.0/quote/user-security-group"
MODIFY_USER_SECURITY_PATH = "/api/v1.0/quote/modify-user-security"
FUTURE_INFO_PATH = "/api/v1.0/quote/future-info"
REFERENCE_FUTURE_PATH = "/api/v1.0/quote/{symbol}/reference-future"
OPTION_VOLATILITY_PATH = "/api/v1.0/quote/{symbol}/option-volatility"
OPTION_EXERCISE_PROBABILITY_PATH = "/api/v1.0/quote/{symbol}/option-exercise-probability"


F10_EARNINGS_PRICE_MOVE_PATH = "/api/v1.0/quote/{symbol}/financials/earnings-price-move"
F10_EARNINGS_PRICE_HISTORY_PATH = "/api/v1.0/quote/{symbol}/financials/earnings-price-history"
F10_STATEMENTS_PATH = "/api/v1.0/quote/{symbol}/financials/statements"
F10_REVENUE_BREAKDOWN_PATH = "/api/v1.0/quote/{symbol}/financials/revenue-breakdown"
F10_ANALYST_CONSENSUS_PATH = "/api/v1.0/quote/{symbol}/research/analyst-consensus"
F10_RATING_SUMMARY_PATH = "/api/v1.0/quote/{symbol}/research/rating-summary"
F10_MORNINGSTAR_PATH = "/api/v1.0/quote/{symbol}/research/morningstar"
F10_VALUATION_DETAIL_PATH = "/api/v1.0/quote/{symbol}/valuation/detail"
F10_VALUATION_PLATE_STOCKS_PATH = "/api/v1.0/quote/valuation/plate-stocks"
F10_VALUATION_INDEX_STOCKS_PATH = "/api/v1.0/quote/valuation/index-stocks"
F10_VALUATION_INDEX_STOCK_PLATES_PATH = "/api/v1.0/quote/valuation/index-stock-plates"
F10_DIVIDENDS_PATH = "/api/v1.0/quote/{symbol}/corporate-actions/dividends"
F10_BUYBACKS_PATH = "/api/v1.0/quote/{symbol}/corporate-actions/buybacks"
F10_SPLITS_PATH = "/api/v1.0/quote/{symbol}/corporate-actions/splits"
F10_SHAREHOLDERS_OVERVIEW_PATH = "/api/v1.0/quote/{symbol}/shareholders/overview"
F10_HOLDING_CHANGES_PATH = "/api/v1.0/quote/{symbol}/shareholders/holding-changes"
F10_HOLDER_DETAIL_PATH = "/api/v1.0/quote/{symbol}/shareholders/holder-detail"
F10_INSTITUTIONAL_PATH = "/api/v1.0/quote/{symbol}/shareholders/institutional"
F10_INSIDER_HOLDERS_PATH = "/api/v1.0/quote/{symbol}/shareholders/insider-holders"
F10_INSIDER_TRADES_PATH = "/api/v1.0/quote/{symbol}/shareholders/insider-trades"
F10_COMPANY_PROFILE_PATH = "/api/v1.0/quote/{symbol}/company/profile"
F10_COMPANY_EXECUTIVES_PATH = "/api/v1.0/quote/{symbol}/company/executives"
F10_COMPANY_EXECUTIVE_BACKGROUND_PATH = "/api/v1.0/quote/{symbol}/company/executive-background"
F10_COMPANY_OPERATIONAL_EFFICIENCY_PATH = ("/api/v1.0/quote/{symbol}/company/"
                                           "operational-efficiency")
F10_TOP_BROKERS_PATH = "/api/v1.0/quote/{symbol}/top-brokers"
F10_TOP_BROKERS_HISTORY_PATH = "/api/v1.0/quote/{symbol}/top-brokers-history"


# ── WP8 任务 2 行情（WP13 任务 0 从内联字面量提升为常量）──────────────────
QUOTE_SNAPSHOT_PATH = "/api/v1.0/quote/snapshot"
STOCK_QUOTE_PATH = "/api/v1.0/quote/stock-quote"
ORDER_BOOK_PATH = "/api/v1.0/quote/order-book"
STOCK_BASICINFO_PATH = "/api/v1.0/quote/stock-basicinfo"
TRADING_DAYS_PATH = "/api/v1.0/quote/trading-days"
MARKET_STATE_PATH = "/api/v1.0/quote/market-state"
FIND_NEWS_PATH = "/api/v1.0/quote/find-news"
FIND_COMMUNITY_PATH = "/api/v1.0/quote/find-community"
OPTION_SCREEN_PATH = "/api/v1.0/quote/option-screen"
CUR_KLINE_PATH = "/api/v1.0/quote/{symbol}/cur-kline"
RT_DATA_PATH = "/api/v1.0/quote/{symbol}/rt-data"
RT_TICKER_PATH = "/api/v1.0/quote/{symbol}/rt-ticker"
HISTORY_KLINE_PATH = "/api/v1.0/quote/{symbol}/history-kline"
CAPITAL_FLOW_PATH = "/api/v1.0/quote/{symbol}/capital-flow"
CAPITAL_FLOW_HISTORY_PATH = "/api/v1.0/quote/{symbol}/capital-flow/history"
CAPITAL_DISTRIBUTION_PATH = "/api/v1.0/quote/{symbol}/capital-distribution"
OPTION_EXPIRATION_PATH = "/api/v1.0/quote/{symbol}/option-expiration"
OPTION_CHAIN_PATH = "/api/v1.0/quote/{symbol}/option-chain"

# ── WP8 任务 3 交易/账户（同上提升）────────────────────────────────────
AUTHORIZED_ACCOUNTS_PATH = "/api/v1.0/accounts/authorized_trd_accs"
ACCOUNT_ORDERS_PATH = "/api/v1.0/accounts/{acc_id}/orders"
ACCOUNT_ORDER_DETAIL_PATH = "/api/v1.0/accounts/{acc_id}/orders/{order_id}"
ACCOUNT_ORDER_CONFIRM_PATH = "/api/v1.0/accounts/{acc_id}/order_confirm"
ACCOUNT_TRADING_INFO_PATH = "/api/v1.0/accounts/{acc_id}/acctradinginfo"
ACCOUNT_ORDERS_HISTORY_PATH = "/api/v1.0/accounts/{acc_id}/orders_history"
ACCOUNT_ORDERS_DETAIL_PATH = "/api/v1.0/accounts/{acc_id}/orders/detail"
ACCOUNT_ORDER_FILLS_PATH = "/api/v1.0/accounts/{acc_id}/order_fills"
ACCOUNT_FILLS_HISTORY_PATH = "/api/v1.0/accounts/{acc_id}/fills_history"
ACCOUNT_FUNDS_PATH = "/api/v1.0/accounts/{acc_id}/funds"
ACCOUNT_POSITIONS_PATH = "/api/v1.0/accounts/{acc_id}/positions"
